ARG DENO_VERSION=1.39.4

FROM denoland/deno:bin-$DENO_VERSION AS deno
FROM node:lts-slim
COPY --from=deno /deno /usr/local/bin/deno

WORKDIR /app
COPY . .

RUN npm install
RUN deno cache src/index.ts

EXPOSE 8787
CMD ["deno", "run", "-A", "./src/index.ts", "--", "run"]
