ARG DENO_VERSION=1.40.2

FROM denoland/deno:bin-$DENO_VERSION AS deno
FROM node:lts-slim
COPY --from=deno /deno /usr/local/bin/deno

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY deps.ts .
RUN npm ci --omit=dev
RUN deno cache deps.ts

COPY . .
RUN deno cache src/index.ts

EXPOSE 8787
CMD ["deno", "run", "-A", "./src/index.ts", "--", "api"]
