# https://github.com/usil/mssql-docker-enhanced/tree/main

name: deno-drizzle-demo
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=drizzle_demo
    healthcheck:
      test: ["CMD-SHELL", "psql -U docker -d drizzle_demo -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  postgres_data:
